#+title: Config
#+author: JD
#+startup: overview

* Build Script
:PROPERTIES:
:header-args: :tangle ../build.sh
:END:
#+begin_src shell
#!/bin/bash
echo "Building hugo..."

hugo -b $CF_PAGES_URL 2>&1
echo "Hugo site built!"

echo "Copying _redirects..."
cp _redirects public/
echo "Redirects copied!"

echo "Build successful"
#+end_src
* Hugo Configuration
:PROPERTIES:
:header-args: :tangle ../hugo.yaml
:END:
This represents my Hugo configuration file. I wanted to keep it in org mode so I could easily document without dealing with comments and structure.
** Motivation
I used [[https://getzola.org][Zola]] for years as my static site generator. It's light weight, very fast and easy to understand however, some features I care about are oddly implemented. Relying on Sublime Syntax highlighting files is an awkward choice in my opinion. I write a lot of emacs lisp in source blocks and there's not a _good_ Sublime syntax I've found for that after searching intermittently for a few years. There also appears to be a lack of motivation to expand to more modern SSG features in an effort to retain simplicity. This is totally ok. I just don't have the desire to engage in heavy modification and configuration of my personal writing platform.

[[https://gohugo.io/][Hugo]] seems to sit at a good middleground of modern SSG features while retaining a simple DX. It also uses Go's [[https://github.com/alecthomas/chroma][Chroma]] module for syntax highlighting, which has amazing support for emacs lisp.

I'd consider moving back to Zola, in fact I'd probably prefer to at some point if they can impelment these key features:
- Tree Sitter based syntax highlighting
- Hook system for building which can provide a good entrypoint for compiling assets or even fetching data if necessary
- A templating system (see [[https://gohugo.io/content-management/archetypes/][Hugos Archetypes]] feature)
- Someone in the community builds an ox-zola package similar to [[https://ox-hugo.scripter.co/][ox-hugo]]. I'm not intelligent enough to build this.

** Initial Configurations
Currently this site is hosted on Cloudflare pages, with a GoDaddy domain, with DNS managed by Cloudeflare. GoDaddy kind of sucks for various reasons and soon enough I plan to migrate ownership to Cloudflares registrar. I'm currently using the [[https://github.com/adityatelange/hugo-PaperMod/tree/master][PaperModX]] theme.

#+begin_src yaml
baseURL: https://jds.work
languageCode: en-us
title: JDs Work
paginate: 5
theme: ["PaperModX"]
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
#+end_src

JSON output is required for search to work properly. HTML & RSS are givens.
#+begin_src yaml
outputs:
  home:
    - HTML
    - RSS
    - JSON

minify:
  disableXML: true
  minifyOutput: true
#+end_src

** Params & Theme config
Currently, I don't know much about the ins and outs of Hugo configuration. AFAICT these are hugo parameters and some theme parameters based on the modules the theme uses.

Set some general configuration parameters. I'm the only author of this blog, so no need to refer to others
#+begin_src yaml
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: JDs Work
  description: "A place to talk about stuff."
  keywords: [Blog, Development, Emacs, Tech]
  author: Me
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
#+end_src

This is more theme specific it seems. These control the features enabled by PaperModX.

Never show social share buttons, at least for now. I don't know if it's worth it or not at the moment. If we _do_ ever enable it only enable Twitter, Mastodon, & Reddit.
#+begin_src yaml
  ShowReadingTime: true
  ShowShareButtons: false
  # ShareButtons: ["twitter", "mastodon", "reddit"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  TocOpen: false
  TocSide: right
#+end_src

I'm using the default favicon system. This isn't tangled.
#+begin_src yaml :tangle no
assets:
  disableHLJS: true # to disable highlight.js
  disableFingerprinting: true
  favicon: "<link / abs url>"
  favicon16x16: "<link / abs url>"
  favicon32x32: "<link / abs url>"
  apple_touch_icon: "<link / abs url>"
  safari_pinned_tab: "<link / abs url>"
#+end_src

#+begin_src yaml
  label:
    text: "JDs Work"
    icon: /apple-touch-icon.png
    iconHeight: 35
#+end_src

Profile mode is a PaperMod setting that will display a splash page before getting to your main content page. I'm not a fan of this. If someone visits my blog I want them to see it's "value" right away and not rely on my personality to get people to engage. Home info mode displays a "blurb" on the index page. I'm generally a fan of this type of introduction, so it's enabled
#+begin_src yaml
  profileMode:
    enabled: false
    title: JDs Work
    subtitle: "A place to write about software development, emacs, and working in the 21st century."
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: |
      I'm a developer based in Fort Worth, Texas. I write about...

      - Software Development
      - Emacs
      - Working in Tech in the 21st Century

      When I'm not working or spending time with my family I'm probably working on my homelab.

      To get in contact, click on one of the links below.
#+end_src

#+begin_src yaml
  socialIcons:
    - name: twitter
      url: "https://x.com/ohimjustjd"
    - name: mastodon
      url: "https://fosstodon.org/@juliusdelta"
    - name: github
      url: "https://github.com/juliusdelta"
    - name: email
      url: "public@jds.work"
    - name: rss
      url: "/index.xml"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/juliusdelta/my-blog/content"
    Text: "Suggest Revision(s)"
    appendFilePath: true
#+end_src

Ignored for now
#+begin_src yaml :tangle no
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"
#+end_src

[[https://fusejs.io/api/options.html][FuseJS]] is the search library implemented by this theme (and maybe Hugo more broadly?) This is just the default configuration. This requires a `JSON` output strategy mentioned above.
#+begin_src yaml
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]
#+end_src

** Site Navigation
I plan to add a few more pages once I understand the intricacies of Hugo. For now these will do.
#+begin_src yaml
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 30
#+end_src

** Syntax Highlighting
Refer to [[https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma][Hugos documentation]] for indepth syntax highlighting options.
#+begin_src yaml
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
#+end_src

* CSS Extensions
:PROPERTIES:
:header-args: :tangle ../assets/css/extended/custom.css
:END:

This is some custom CSS that overrides a few things in PaperModX theme.
#+begin_src css
/* Add something soon */
#+end_src
